config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'category#index', as: 'home'
  resources :category
  resources :product do
    post 'add_to_cart'
  end

  resources :order

  post '/order/check_coupon' => 'order#check_coupon'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  has_many :order
end

app/models/voucher.rb
class Voucher < ApplicationRecord
  has_many :orders
  validates :code, presence: true, uniqueness: true

  scope :valid, -> { where('qty > 0 and starts_at <= ? and expires_at >= ?', Time.now, Time.now) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :get_categories

  def index
    session[:cart] = [] unless session[:cart].present?
    get_categories
  end

  def get_categories
    @categories = Category.where(active: true)
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def show
    @products = Category.find(params[:id]).product
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController

  def index
    @products = session[:cart]
    @total = PaymentService::CaculatorFeeTax.new(@products).execute
  end

  def check_coupon
    @result = VoucherService::CheckVoucher.new(params[:code]).execute

    products = session[:cart]
    if @result[:exist]
      total = PaymentService::CaculatorFeeTax.new(products, params[:code]).execute
      @result[:total] = total
    end

    @result
  end

  def create
    order = OrderService::CreateOrder.new(params).execute

    if order.persisted?
      @result = {success: true}
    else
      @result = {success: false}
    end
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    session[:cart].push({ id: params[:id],
                          name: params[:name],
                          quantity: params[:quantity],
                          price: params[:price] })

    size = session[:cart].length
    @result = { success: true, message: 'Add success', cart_size: size }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/category/index.html.erb
<div class="album py-5">
  <div class="row">
    <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
        <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        <div class="card-body">
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
              <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
            </div>
            <small class="text-muted">9 mins</small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/category/show.html.erb
<div class="album py-5">
  <div class="row">
    <% @products.each do |product|%>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
           <img width="100%" height="255" src="<%= product.image %>" class="rounded" alt="food">
          <div class="card-body">
            <p class="card-text"><%=product.name%></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <%= link_to "View", product_path(product.id), class: "btn btn-sm btn-outline-secondary" %>
                <%= link_to "Edit", edit_product_path(product.id), class: "btn btn-sm btn-outline-secondary" %>
              </div>
              <small class="text-muted">9 mins</small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Order Food</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.3.1.slim.min.js'%>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <%= link_to "Order Food", "/category", class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <% @categories.each do |category| %>
            <li class="nav-item">
              <%= link_to category.name, category_path(category.id), class: "nav-link" %>
          </li>
          <% end %>
          
        </ul>
        <%= form_tag("/order", method: "get", class: "form-inline my-2 my-lg-0" ) do %>
          <input class="form-control mr-sm-2 search" type="text" placeholder="Search" aria-label="Search">
          <div class="cart">
            <button type="submit" class="btn btn-default btn-sm btn-add-to-cart">
              <% if session[:cart].present?%>
                <span id="cart-size"><%= session[:cart].length%></span> x
              <% end %>
              <span class="glyphicon glyphicon-shopping-cart"></span>
                Cart
            </button>
          </div>
        <%end%>
      </div>
    </nav>

    <main role="main" class="container">
      <%= yield %>
    </main>
  
    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a href="/docs/4.3/getting-started/introduction/">getting started guide</a>.</p>
      </div>
    </footer>
  </body>
</html>

app/views/order/index.html.erb
<div id="order__products">
  <div class="form-row">
    <div class="col-md-4 mb-3">
      <label for="firstName">First name</label>
      <input type="text" class="form-control" id="firstName" placeholder="First name">
    </div>
    <div class="col-md-4 mb-3">
      <label for="lastName">Last name</label>
      <input type="text" class="form-control" id="lastName" placeholder="Last name">
    </div>
    <div class="col-md-4 mb-3">
      <label for="email">Email</label>
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text" id="inputGroupPrepend2">@</span>
        </div>
        <input type="text" class="form-control" id="email" placeholder="Email">
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="col-md-6 mb-3">
      <label for="address">Address</label>
      <input type="text" class="form-control" id="address" placeholder="Address">
    </div>

    <div class="col-md-2">
      <label for="voucherCode">Voucher Code</label>
      <input type="text" class="form-control" id="voucherCode" placeholder="Code" required>
    </div>

    <div class="col-md-2">
      <label for="submitVoucher" class="invisible" >Voucher Code</label>
      <button class="btn btn-warning" id="submitVoucher">Check your code</button>
      <span class="text-danger coupon-message" id="voucherMessage"></span>
    </div>
  </div>
  <ul class="list-group">
    <% session[:cart].each do |product|%>
      <li class="list-group-item d-flex justify-content-between align-items-center col-md-5">
        <%= product["name"]%>
        <span class="badge badge-primary badge-pill"><%= product["quantity"]%></span>
        <%= product["price"].to_f * product["quantity"].to_i %>$
      </li>
    <% end %>
  </ul>
  <div class="pt-4 pb-4">
    Total: <span id="total"><%= @total%></span>$
  </div>
  <button class="btn btn-primary mb-5" id="payment">Payment</button>
</div>

app/views/product/_label_value.html.erb
  <div class="inline-label-value">
    <strong class="inline-label-value__label"><%= product_label%> : </strong>
    <div class="inline-lable-value__value"><%= product_value %></div>
  </div>

app/views/product/show.html.erb
<div id="category__product">
  <h2>PRODUCT</h2>

  <div>
    <img src="<%= @product.image%>" class="rounded product__image" alt="food">
  </div>

  <%= render partial: "label_value", locals: { product_label: "Name", product_value: @product.name } %>
  <%= render partial: "label_value", locals: { product_label: "Description", product_value: @product.description } %>
  <%= render partial: "label_value", locals: { product_label: "Price", product_value: @product.price } %>

  <div class="d-flex justify-content-between align-items-center product__add-to-cart">
    <div class="btn-group">
      <span class= "btn btn-sm btn-outline-secondary product__btn-increase" >
        <strong class="product__btn-adjust">+</strong>
      </span>
      <input type="text" name="quantity" class="product__quantity" value="1" />
      <span class= "btn btn-sm btn-outline-secondary product__btn-decrease" >
        <strong class="product__btn-adjust">-</strong>
      </span>
    </div>
    <div class="group-add-to-cart">
      <button type="submit" class="btn btn-default btn-sm btn-add-to-cart">
        <span class="glyphicon glyphicon-shopping-cart"></span>
        Add To Cart
      </button>
    </div>
  </div>

   <%#-----HIDDEN VALUE----- %>
   <input class="hidden" value="<%= @product.id%>" id="product_id" />
   <input class="hidden" value="<%= @product.price%>" id="product_price" />
   <input class="hidden" value="<%= @product.name%>" id="product_name" />

</div>